import {VariantProps} from "tailwind-variants";

import {tv} from "../utils/tv";
import {colorVariants} from "../utils";

const typography = tv({
  slots: {
    h1: "",
    h2: "",
    h3: "",
    h4: "",
    h5: "",
    h6: "",
    subtitle1: "",
    subtitle2: "",
    body1: "",
    body2: "",
    buttonLarge: "",
    buttonMedium: "",
    buttonSmall: "",
    caption: "",
    overline: "",
  },
  variants: {
    variant: {
      h1: "font-bold text-4xl leading-tight tracking-tight",
      h2: "font-bold text-3xl leading-snug tracking-tighter",
      h3: "font-bold text-2xl leading-normal",
      h4: "font-bold text-xl leading-tight tracking-wide",
      h5: "font-bold text-lg leading-normal",
      h6: "font-medium text-base leading-relaxed tracking-wide",
      subtitle1: "font-bold text-lg leading-normal tracking-wide",
      subtitle2: "font-medium text-base leading-relaxed tracking-wide",
      body1: "font-normal text-lg leading-normal tracking-wide",
      body2: "font-normal text-base leading-snug tracking-wide",
      buttonLarge: "font-normal text-lg leading-normal tracking-wide",
      buttonMedium: "font-normal text-base leading-normal tracking-wide",
      buttonSmall: "font-normal text-sm leading-snug tracking-wide",
      caption: "font-normal text-sm leading-snug tracking-wide",
      overline: "font-normal text-sm leading-snug tracking-wide",
    },
    color: {
      neutral: {
        h1: colorVariants.typography["neutral"],
        h2: colorVariants.typography["neutral"],
        h3: colorVariants.typography["neutral"],
        h4: colorVariants.typography["neutral"],
        h5: colorVariants.typography["neutral"],
        h6: colorVariants.typography["neutral"],
        subtitle1: colorVariants.typography["neutral"],
        subtitle2: colorVariants.typography["neutral"],
        body1: colorVariants.typography["neutral"],
        body2: colorVariants.typography["neutral"],
        buttonLarge: colorVariants.typography["neutral"],
        buttonMedium: colorVariants.typography["neutral"],
        buttonSmall: colorVariants.typography["neutral"],
        caption: colorVariants.typography["neutral"],
        overline: colorVariants.typography["neutral"],
      },
      "neutral-medium": {
        h1: colorVariants.typography["neutral-medium"],
        h2: colorVariants.typography["neutral-medium"],
        h3: colorVariants.typography["neutral-medium"],
        h4: colorVariants.typography["neutral-medium"],
        h5: colorVariants.typography["neutral-medium"],
        h6: colorVariants.typography["neutral-medium"],
        subtitle1: colorVariants.typography["neutral-medium"],
        subtitle2: colorVariants.typography["neutral-medium"],
        body1: colorVariants.typography["neutral-medium"],
        body2: colorVariants.typography["neutral-medium"],
        buttonLarge: colorVariants.typography["neutral-medium"],
        buttonMedium: colorVariants.typography["neutral-medium"],
        buttonSmall: colorVariants.typography["neutral-medium"],
        caption: colorVariants.typography["neutral-medium"],
        overline: colorVariants.typography["neutral-medium"],
      },
      "neutral-light": {
        h1: colorVariants.typography["neutral-light"],
        h2: colorVariants.typography["neutral-light"],
        h3: colorVariants.typography["neutral-light"],
        h4: colorVariants.typography["neutral-light"],
        h5: colorVariants.typography["neutral-light"],
        h6: colorVariants.typography["neutral-light"],
        subtitle1: colorVariants.typography["neutral-light"],
        subtitle2: colorVariants.typography["neutral-light"],
        body1: colorVariants.typography["neutral-light"],
        body2: colorVariants.typography["neutral-light"],
        buttonLarge: colorVariants.typography["neutral-light"],
        buttonMedium: colorVariants.typography["neutral-light"],
        buttonSmall: colorVariants.typography["neutral-light"],
        caption: colorVariants.typography["neutral-light"],
        overline: colorVariants.typography["neutral-light"],
      },
      white: {
        h1: colorVariants.typography["white"],
        h2: colorVariants.typography["white"],
        h3: colorVariants.typography["white"],
        h4: colorVariants.typography["white"],
        h5: colorVariants.typography["white"],
        h6: colorVariants.typography["white"],
        subtitle1: colorVariants.typography["white"],
        subtitle2: colorVariants.typography["white"],
        body1: colorVariants.typography["white"],
        body2: colorVariants.typography["white"],
        buttonLarge: colorVariants.typography["white"],
        buttonMedium: colorVariants.typography["white"],
        buttonSmall: colorVariants.typography["white"],
        caption: colorVariants.typography["white"],
        overline: colorVariants.typography["white"],
      },
      primary: {
        h1: colorVariants.typography["primary"],
        h2: colorVariants.typography["primary"],
        h3: colorVariants.typography["primary"],
        h4: colorVariants.typography["primary"],
        h5: colorVariants.typography["primary"],
        h6: colorVariants.typography["primary"],
        subtitle1: colorVariants.typography["primary"],
        subtitle2: colorVariants.typography["primary"],
        body1: colorVariants.typography["primary"],
        body2: colorVariants.typography["primary"],
        buttonLarge: colorVariants.typography["primary"],
        buttonMedium: colorVariants.typography["primary"],
        buttonSmall: colorVariants.typography["primary"],
        caption: colorVariants.typography["primary"],
        overline: colorVariants.typography["primary"],
      },
      success: {
        h1: colorVariants.typography["success"],
        h2: colorVariants.typography["success"],
        h3: colorVariants.typography["success"],
        h4: colorVariants.typography["success"],
        h5: colorVariants.typography["success"],
        h6: colorVariants.typography["success"],
        subtitle1: colorVariants.typography["success"],
        subtitle2: colorVariants.typography["success"],
        body1: colorVariants.typography["success"],
        body2: colorVariants.typography["success"],
        buttonLarge: colorVariants.typography["success"],
        buttonMedium: colorVariants.typography["success"],
        buttonSmall: colorVariants.typography["success"],
        caption: colorVariants.typography["success"],
        overline: colorVariants.typography["success"],
      },
      warning: {
        h1: colorVariants.typography["warning"],
        h2: colorVariants.typography["warning"],
        h3: colorVariants.typography["warning"],
        h4: colorVariants.typography["warning"],
        h5: colorVariants.typography["warning"],
        h6: colorVariants.typography["warning"],
        subtitle1: colorVariants.typography["warning"],
        subtitle2: colorVariants.typography["warning"],
        body1: colorVariants.typography["warning"],
        body2: colorVariants.typography["warning"],
        buttonLarge: colorVariants.typography["warning"],
        buttonMedium: colorVariants.typography["warning"],
        buttonSmall: colorVariants.typography["warning"],
        caption: colorVariants.typography["warning"],
        overline: colorVariants.typography["warning"],
      },
      danger: {
        h1: colorVariants.typography["danger"],
        h2: colorVariants.typography["danger"],
        h3: colorVariants.typography["danger"],
        h4: colorVariants.typography["danger"],
        h5: colorVariants.typography["danger"],
        h6: colorVariants.typography["danger"],
        subtitle1: colorVariants.typography["danger"],
        subtitle2: colorVariants.typography["danger"],
        body1: colorVariants.typography["danger"],
        body2: colorVariants.typography["danger"],
        buttonLarge: colorVariants.typography["danger"],
        buttonMedium: colorVariants.typography["danger"],
        buttonSmall: colorVariants.typography["danger"],
        caption: colorVariants.typography["danger"],
        overline: colorVariants.typography["danger"],
      },
    },
  },
  defaultVariants: {
    variant: "body1",
    color: "neutral",
  },
  compoundVariants: [],
});

export type TypographyVariantProps = VariantProps<typeof typography>;
export type TypographySlots = keyof ReturnType<typeof typography>;

export {typography};
